language: node_js
node_js:
    - '10'
sudo: false
branches:
    only:
        - master
os:
    - linux
cache:
    directories:
        - node_modules
install:
    - yarn install
script:
    - yarn run lint
    - yarn run build
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: build
    on:
        branch: master
